name: CI/CD Pipeline

# 1. THE TRIGGERS: Run on pushes and PRs to dev and main
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test-api:
    name: Run Newman API Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      # Run your 50 tests. Ensure Postman is pointing to your staging/local setup as needed.
      - name: Run API Tests
        run: newman run cart_collection.json -e prod_env.json --iteration-count 10

  deploy:
    name: Deploy to AWS EC2
    #needs: test-api  # This is the safety valve. It MUST pass tests first.
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Strictly blocks deployment from the 'dev' branch

    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd CART
            git fetch origin
            git reset --hard origin/main
            
            sudo docker stop live-cart-api || true
            sudo docker rm live-cart-api || true
            sudo docker build -t cart-api .
            
            # This injects your new RDS Postgres URL directly into the app at runtime
            sudo docker run -d -p 80:8000 --name live-cart-api -e DATABASE_URL="${{ secrets.DATABASE_URL }}" cart-api